name: Deploy to Cloud Run
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - uses: google-github-actions/setup-gcloud@v2
    - run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet
    - run: docker build -t asia-south1-docker.pkg.dev/onyx-stack-474405-h5/bankpoint-backend/bankpoint-backend:latest .
    - run: gcloud artifacts docker images list asia-south1-docker.pkg.dev/onyx-stack-474405-h5/bankpoint-backend --quiet || true
    - run: docker push asia-south1-docker.pkg.dev/onyx-stack-474405-h5/bankpoint-backend/bankpoint-backend:latest
    - uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: bankpoint-backend
        region: asia-south1
        image: asia-south1-docker.pkg.dev/onyx-stack-474405-h5/bankpoint-backend/bankpoint-backend:latest
        secrets: |
          FIREBASE_CREDENTIALS=firebase-credentials:latest